"""Shared Jellyfin and Navidrome provider fixtures for the 1.6.0 Jellyfin tests.

``navidrome_catalog`` is a rich OpenSubsonic payload. Its normalized form is
pinned byte-for-byte in ``navidrome_normalization_golden.json``, generated by
the 1.5.0 normalizer (f367ffb), so no Jellyfin change can alter a Navidrome
catalogue.
"""

import copy
from contextlib import nullcontext
from types import SimpleNamespace


SERVER_A = "5e0d2fd1c1b54d4ca1d2b9d2a2c7e4f1"
SERVER_B = "0f9e8d7c6b5a49382716a5b4c3d2e1f0"
LIB_A = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
LIB_B = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"


def jid(label):
    """A deterministic 32-hex Jellyfin item ID for a readable label."""
    import hashlib

    return hashlib.md5(label.encode("utf-8")).hexdigest()


def jellyfin_track_item(label, album_label="album", artist="Artist", album_artist=None,
                        index=1, disc=1, image=False, album_image=True, extra=None):
    album_artist = album_artist or artist
    item = {
        "Name": label.title(),
        "ServerId": SERVER_A,
        "Id": jid(label),
        "Path": f"/music/{album_label}/{label}.flac",
        "Type": "Audio",
        "MediaType": "Audio",
        "IsFolder": False,
        "AlbumId": jid(album_label),
        "Album": album_label.title(),
        "AlbumArtist": album_artist,
        "AlbumArtists": [{"Name": album_artist, "Id": jid(f"artist:{album_artist}")}],
        "Artists": [artist],
        "ArtistItems": [{"Name": artist, "Id": jid(f"artist:{artist}")}],
        "IndexNumber": index,
        "ParentIndexNumber": disc,
        "RunTimeTicks": 2_000_000_000 + index,
        "ProductionYear": 2001,
        "PremiereDate": "2001-05-01T00:00:00.0000000Z",
        "Genres": ["Rock"],
        "ProviderIds": {
            "MusicBrainzRecording": f"rec-{label}",
            "MusicBrainzTrack": f"reltrack-{label}",
            "MusicBrainzAlbum": f"release-{album_label}",
        },
        "ImageTags": {"Primary": f"tag-{label}"} if image else {},
        "ImageBlurHashes": {"Primary": {"x": "LKO2?U%2Tw=w]~RBVZRi};RPxuwH"}},
        "AlbumPrimaryImageTag": f"tag-{album_label}" if album_image else None,
        "DateCreated": "2026-01-02T03:04:05.0000000Z",
        "SortName": label,
        "ParentId": jid(f"folder:{album_label}"),
        "Container": "flac",
        "UserData": {"PlayCount": 9, "IsFavorite": True, "Key": "secret"},
        "MediaSources": [
            {
                "Protocol": "File",
                "Id": jid(label),
                "Path": f"/music/{album_label}/{label}.flac",
                "Container": "flac",
                "Size": 30_000_000 + index,
                "Bitrate": 1_000_000,
                "MediaStreams": [
                    {"Type": "Audio", "Codec": "flac", "BitRate": 1_000_000,
                     "SampleRate": 44100, "BitDepth": 16, "Channels": 2,
                     "ChannelLayout": "stereo", "Index": 0},
                    {"Type": "EmbeddedImage", "Codec": "mjpeg", "Index": 1},
                ],
            }
        ],
    }
    item.update(extra or {})
    return item


def jellyfin_album_item(album_label, album_artist="Artist", image=True):
    return {
        "Name": album_label.title(),
        "ServerId": SERVER_A,
        "Id": jid(album_label),
        "Type": "MusicAlbum",
        "MediaType": "Unknown",
        "AlbumArtist": album_artist,
        "AlbumArtists": [{"Name": album_artist, "Id": jid(f"artist:{album_artist}")}],
        "ArtistItems": [{"Name": "Someone Else", "Id": jid("artist:Someone Else")}],
        "ProductionYear": 2001,
        "Genres": ["Rock"],
        "ProviderIds": {"MusicBrainzAlbum": f"release-{album_label}",
                        "MusicBrainzReleaseGroup": f"rg-{album_label}"},
        "ImageTags": {"Primary": f"tag-{album_label}"} if image else {},
        "DateCreated": "2026-01-02T03:04:05.0000000Z",
        "SortName": album_label,
        "Path": f"/music/{album_label}",
        "UserData": {"PlayCount": 3},
    }


class FakeResponse:
    def __init__(self, body, status=200):
        self.body = body
        self.status_code = status
        self.text = body if isinstance(body, str) else ""

    def raise_for_status(self):
        if self.status_code >= 400:
            raise RuntimeError(f"HTTP {self.status_code}")

    def json(self):
        return copy.deepcopy(self.body)

    def close(self):
        pass


class FakeJellyfinHttp:
    """Serves Jellyfin 12.2 answers as measured on a real server (2026-10-06).

    ``/Items`` pages per (ParentId, IncludeItemTypes); ``/Artists`` and
    ``/Artists/AlbumArtists`` per ParentId, listing the MusicArtist items
    credited on that library's tracks (ArtistItems) or as album artists, with
    their image tags from ``artists``; a library in ``forbidden`` answers 401
    with Jellyfin's "not permitted" body, one in ``unknown`` 400.
    ``public`` is one ``/System/Info/Public`` body, or a list of
    ``(status, body)`` answers served in turn.
    """

    def __init__(self, base, libraries, artists=None, public=None, fail_artists=False,
                 forbidden=(), unknown=(), unauthorized=False):
        self.base = base
        self.libraries = libraries  # {library_id: {"Audio": [...], "MusicAlbum": [...]}}
        self.artists = artists or {}  # {artist_id: item}
        self.public = public
        self.fail_artists = fail_artists
        self.forbidden = set(forbidden)
        self.unknown = set(unknown)
        self.unauthorized = unauthorized
        self.calls = []

    def _public(self):
        if isinstance(self.public, list):
            status, body = self.public.pop(0)
            return FakeResponse(body, status)
        return FakeResponse(self.public)

    def _artists(self, library_id, album_artists):
        rows = self.libraries[library_id]
        credited = {}
        for item in rows.get("Audio", []) + rows.get("MusicAlbum", []):
            keys = ("AlbumArtists",) if album_artists else ("ArtistItems",)
            if item.get("Type") == "MusicAlbum" and not album_artists:
                continue
            for key in keys:
                for artist in item.get(key) or []:
                    credited[artist["Id"]] = artist["Name"]
        return [
            self.artists.get(artist_id) or {"Id": artist_id, "Name": name,
                                            "Type": "MusicArtist", "ImageTags": {}}
            for artist_id, name in sorted(credited.items(), key=lambda pair: pair[1])
        ]

    def get(self, url, headers=None, params=None, timeout=None, **_kwargs):
        self.calls.append({"url": url, "headers": dict(headers or {}), "params": dict(params or {}),
                           "timeout": timeout})
        params = params or {}
        if url == f"{self.base}/System/Info/Public":
            return self._public()
        if self.unauthorized:
            return FakeResponse("", 401)
        library_id = params.get("ParentId")
        if library_id in self.forbidden:
            return FakeResponse(
                f"lumae-listener is not permitted to access Library {library_id}.", 401)
        if library_id in self.unknown:
            return FakeResponse("Error processing request.", 400)
        start, limit = int(params["StartIndex"]), int(params["Limit"])
        if url in (f"{self.base}/Artists", f"{self.base}/Artists/AlbumArtists"):
            if self.fail_artists:
                raise RuntimeError("artist lookup failed: http://user:token@host")
            rows = self._artists(library_id, url.endswith("/AlbumArtists"))
            return FakeResponse({"Items": rows[start:start + limit]})
        assert url == f"{self.base}/Items", url
        rows = self.libraries[library_id][params["IncludeItemTypes"]]
        return FakeResponse({"Items": rows[start:start + limit]})


class FakeJellyfinModule:
    """The AudioMuse ``tasks.mediaserver.jellyfin`` surface the reader uses."""

    def __init__(self, http, libraries, target=None, base="http://jellyfin.test:8096",
                 token="server-token"):
        self.requests = http
        self._libraries = libraries
        self._target = target
        self._base = base
        self._token = token

    def list_libraries(self):
        return [dict(row) for row in self._libraries]

    def _get_target_library_ids(self):
        return None if self._target is None else set(self._target)

    def _jellyfin_base_url(self):
        return self._base

    def _jellyfin_headers_from_creds(self):
        return {"Authorization": f'MediaBrowser Token="{self._token}"'}

    def _jellyfin_user_id(self):
        return "user-1"


class FakeCore:
    def __init__(self, servers, modules):
        self.servers = servers
        self.modules = modules
        self.bound = []

    def list_servers(self):
        return list(self.servers)

    def bind(self, server_id):
        self.bound.append(server_id)
        return nullcontext()

    def provider_module(self, provider_type):
        return self.modules[provider_type]


def jellyfin_library_rows():
    return [{"id": LIB_A, "name": "Music"}, {"id": LIB_B, "name": "Classical"}]


def jellyfin_raw_catalog(track_labels=("one", "two"), album="album", library=LIB_A, extra=None):
    """A raw Jellyfin catalogue as ``jellyfin_provider.fetch_catalog`` returns it."""
    from plugins.LumaeAnalysis import jellyfin_provider

    tracks = [
        jellyfin_provider.track_row(
            jellyfin_track_item(label, album, index=index + 1,
                                extra=(extra or {}).get(label)), [library])
        for index, label in enumerate(track_labels)
    ]
    albums = [jellyfin_provider.album_row(jellyfin_album_item(album), [library])]
    return {
        "libraries": [{"id": library, "name": "Music"}],
        "albums": albums,
        "tracks": tracks,
        "artist_cover_art": {jid("artist:Artist"): jid("artist:Artist")},
    }


class JellyfinBridge:
    """A credential-free bridge double for one Jellyfin AudioMuse server."""

    def __init__(self, raw, server_id=SERVER_A, version="12.2.0", product="Jellyfin Server",
                 server_type="jellyfin", core=None):
        self.raw = raw
        self.identity = {
            "provider_type": server_type,
            "server_type": server_type,
            "server_version": version,
            "server_id": server_id,
            "product_name": product,
        }
        self.server_type = server_type
        self.fetches = 0
        self.probe_error = None
        self.core = core

    def list_servers(self):
        return [self.require_server("server-j")]

    def require_server(self, server_id):
        assert server_id == "server-j"
        return {"server_id": "server-j", "name": "Jelly", "provider_type": self.server_type,
                "is_default": True, "supported": True}

    def fetch_catalog(self, server_id):
        self.fetches += 1
        return copy.deepcopy(self.raw)

    def probe_server_identity(self, server_id):
        if self.probe_error:
            raise self.probe_error
        return dict(self.identity)


def navidrome_catalog():
    """A rich OpenSubsonic payload as the Navidrome reader returns it."""
    return {
        "libraries": [{"id": "1", "name": "Music"}, {"id": "2", "name": "Audiobooks"}],
        "albums": [
            {
                "id": "al-1",
                "name": "Album One",
                "artist": "Band",
                "artistId": "ar-1",
                "coverArt": "al-1_0",
                "songCount": 2,
                "duration": 400,
                "created": "2026-01-01T00:00:00Z",
                "year": 1999,
                "genre": "Rock",
                "genres": [{"name": "Rock"}],
                "sortName": "album one",
                "musicBrainzId": "mbid-release",
                "isCompilation": False,
                "releaseTypes": ["Album"],
                "originalReleaseDate": {"year": 1998, "month": 3, "day": 2},
                "discTitles": [{"disc": 1, "title": "Side A"}],
                "explicitStatus": "clean",
                "artists": [{"id": "ar-1", "name": "Band"}],
                "_lumae_library_ids": ["1"],
            }
        ],
        "tracks": [
            {
                "id": "tr-1",
                "parent": "al-1",
                "isDir": False,
                "title": "First",
                "album": "Album One",
                "artist": "Band feat. Guest",
                "track": 1,
                "year": 1999,
                "genre": "Rock",
                "coverArt": "mf-tr-1_0",
                "size": 9_000_000,
                "contentType": "audio/flac",
                "suffix": "flac",
                "duration": 200,
                "bitRate": 900,
                "bitDepth": 16,
                "samplingRate": 44100,
                "channelCount": 2,
                "path": "Band/Album One/01 First.flac",
                "discNumber": 1,
                "created": "2026-01-01T00:00:00Z",
                "albumId": "al-1",
                "artistId": "ar-1",
                "type": "music",
                "mediaType": "song",
                "bpm": 120,
                "comment": "",
                "sortName": "first",
                "musicBrainzId": "mbid-recording-1",
                "isrc": ["USABC9900001"],
                "genres": [{"name": "Rock"}],
                "artists": [{"id": "ar-1", "name": "Band"}, {"id": "ar-2", "name": "Guest"}],
                "displayArtist": "Band feat. Guest",
                "albumArtists": [{"id": "ar-1", "name": "Band"}],
                "displayAlbumArtist": "Band",
                "contributors": [
                    {"role": "composer", "artist": {"id": "ar-3", "name": "Writer"}},
                    {"role": "performer", "subRole": "guitar",
                     "artist": {"id": "ar-2", "name": "Guest"}},
                ],
                "displayComposer": "Writer",
                "moods": ["happy"],
                "replayGain": {"trackGain": -6.5, "albumGain": -7.1, "trackPeak": 0.98,
                               "albumPeak": 0.99},
                "explicitStatus": "clean",
                "playCount": 4,
                "userRating": 5,
                "_lumae_library_ids": ["1"],
            },
            {
                "id": "tr-2",
                "title": "Second",
                "album": "Album One",
                "artist": "Band",
                "track": 2,
                "discNumber": 1,
                "duration": 200.5,
                "suffix": "mp3",
                "bitRate": 320,
                "albumId": "al-1",
                "artistId": "ar-1",
                "musicFolderId": "1",
            },
        ],
        "artist_cover_art": {"ar-1": "ar-1_0", "ar-2": ""},
    }


def bridge_with_core(servers, modules):
    from plugins.LumaeAnalysis.catalog_providers import ProviderCatalogBridge

    return ProviderCatalogBridge(core_adapter=FakeCore(servers, modules))


def jellyfin_server(server_id="server-j", provider_type="jellyfin"):
    return {"server_id": server_id, "name": "Jelly", "provider_type": provider_type,
            "is_default": True}


def jellyfin_public(server_id=SERVER_A, version="12.2.0", product="Jellyfin Server"):
    return {"LocalAddress": "http://10.0.0.2:8096", "ServerName": "jelly", "Version": version,
            "ProductName": product, "OperatingSystem": "", "Id": server_id,
            "StartupWizardCompleted": True}


__all__ = [name for name in dir() if not name.startswith("_")] + ["SimpleNamespace"]
